tsconfig.json, web/next.config.js, web/next.config.test.ts
https://nicedigital.atlassian.net/browse/NXT-6
=> NXT-6 Add security-headers

jest.config.js, web/global.d.ts, web/jest.setup.ts, web/package-lock.json, web/package.json, web/src/pages/_app.page.tsx, web/src/pages/_app.test.tsx, web/src/pages/_document.page.tsx, web/src/pages/guidance/indevelopment.page.tsx
https://nicedigital.atlassian.net/browse/NXT-9
=> NXT-9 Add GTM snippet

web/config/default.yml, web/next.config.js, web/next.config.test.ts, web/package-lock.json, web/package.json, web/src/components/GoogleTagManager/GoogleTagManager.test.tsx, web/src/components/GoogleTagManager/GoogleTagManager.tsx, web/src/config/config.ts, web/src/pages/_app.page.tsx, web/src/pages/_app.test.tsx, web/src/pages/_document.page.tsx
https://nicedigital.atlassian.net/browse/NXT-8
=> NXT-8 Add cookie banner

web/src/pages/status.page.tsx
https://nicedigital.atlassian.net/browse/NXT-15
=> NXT-15 Add static status page

.vscode/extensions.json, README.md, web-host/.gitignore, web-host/Deploy.ps1, web-host/NICE.NextWeb.WebHost.nuspec, web-host/README.md, web-host/package-lock.json, web-host/package.json, web-host/pm2.ecosystem.json, web-host/pm2.start.js, web/NICE.NextWeb.WebSite.nuspec, web/README.md, web/package-lock.json, web/package.json, web/start.js
https://nicedigital.atlassian.net/browse/NXT-16
=> NXT-16 Separate web site from web host

.editorconfig
https://nicedigital.atlassian.net/browse/NXT-37
=> NX-37 Fix issues with editorconfig and cs files

web-host/Deploy.ps1
https://nicedigital.atlassian.net/browse/NXT-40
=> NXT-40 Fix hanging Octo deployment

web/next.config.js, web/package.json
https://nicedigital.atlassian.net/browse/NXT-44
=> NXT-44 Fix JS in IE11

web/src/components/GuidanceListFilters/__snapshots__/GuidanceListFilters.test.tsx.snap, web/src/components/ToFromDateFilters/ToFromDateFilters.test.tsx, web/src/components/ToFromDateFilters/ToFromDateFilters.tsx
https://nicedigital.atlassian.net/browse/NXT-49
=> NXT-49 Change to date to maximum of today

api/NICE.NextWeb.API/Controllers/ErrorController.cs, api/NICE.NextWeb.API/Controllers/ErrorTestController.cs, api/NICE.NextWeb.API/Controllers/HomeController.cs, api/NICE.NextWeb.API/Startup.cs, api/NICE.NextWeb.API/Views/Home/Index.cshtml
https://nicedigital.atlassian.net/browse/NXT-52
=> NXT-52 Add error handing and error testing controller

web/src/pages/guidance/published.page.test.tsx, web/src/pages/guidance/published.page.tsx
https://nicedigital.atlassian.net/browse/NXT-53
=> NXT-53 Don't index 0 results

web/package-lock.json, web/package.json, web/src/components/GuidanceListPage/redirects.test.ts, web/src/components/GuidanceListPage/redirects.ts, web/src/pages/guidance/published.page.test.tsx, web/src/pages/guidance/published.page.tsx
https://nicedigital.atlassian.net/browse/NXT-38
=> NXT-38 Add list page redirects

web/src/components/GuidanceListPage/GuidanceListGetServerSideProps/GuidanceListGetServerSideProps.test.ts, web/src/components/GuidanceListPage/GuidanceListGetServerSideProps/GuidanceListGetServerSideProps.ts
https://nicedigital.atlassian.net/browse/NXT-54
=> NXT-54 Add server timing header for list pages

web/src/pages/_app.page.tsx, web/src/pages/guidance/__tests__/__snapshots__/inconsultation.page.test.tsx.snap, web/src/pages/guidance/__tests__/__snapshots__/indevelopment.page.test.tsx.snap, web/src/pages/guidance/__tests__/__snapshots__/proposed.page.test.tsx.snap, web/src/pages/guidance/__tests__/__snapshots__/published.page.test.tsx.snap
https://nicedigital.atlassian.net/browse/NXT-66
Bit of a hack to make Axe/Lighthouse tests pass - see comment within the code
=> NXT-66 Fix incorrect aria attribute

web/package-lock.json, web/package.json
https://nicedigital.atlassian.net/browse/NXT-70
=> NXT-70 Update global nav to load from npm

web/src/components/GuidanceListPage/GuidanceListPage.test.tsx, web/src/components/GuidanceListPage/GuidanceListPage.tsx, web/src/pages/guidance/inconsultation.page.tsx, web/src/pages/guidance/indevelopment.page.tsx, web/src/pages/guidance/proposed.page.tsx, web/src/pages/guidance/published.page.tsx
https://nicedigital.atlassian.net/browse/NXT-68
=> NXT-68 Add meta descriptions

api/NICE.NextWeb.API/ScheduledTasks/Niceorg/RefreshGuidanceTaxonomyScheduledTask.cs
https://nicedigital.atlassian.net/browse/NXT-85
=> NXT-85 Fix issues with Taxonomy Refresh task

web/package-lock.json, web/package.json, web/src/pages/_app.test.tsx
https://nicedigital.atlassian.net/browse/NXT-78
=> NXT-78 Bump global nav to meganav

web/package-lock.json, web/package.json
https://nicedigital.atlassian.net/browse/NXT-95
=> NXT-95 Bump global-nav version

web/package-lock.json, web/package.json
https://nicedigital.atlassian.net/browse/NXT-96
=> NXT-96 Bump Global Nav

web/next.config.js, web/package-lock.json, web/package.json
https://nicedigital.atlassian.net/browse/NXT-103
=> NXT-103 Bump GN version for CKS advice wording

api/NICE.NextWeb.API/NICE.NextWeb.API.csproj
https://nicedigital.atlassian.net/browse/NXT-93
=> NXT-93 Set ASP.NET environment variable

web/package-lock.json, web/package.json
https://nicedigital.atlassian.net/browse/NXT-107
=> NXT-107 Bump global nav version to latest

web/package-lock.json, web/package.json
https://nicedigital.atlassian.net/browse/NXT-111
=> NXT-111 GN version bump

web/src/components/PublicationsChapterMenu/PublicationsChapterMenu.test.tsx, web/src/components/PublicationsChapterMenu/PublicationsChapterMenu.tsx, web/src/components/PublicationsPrevNext/PublicationsPrevNext.tsx, web/src/pages/indicators/[slug]/index.page.test.tsx
https://nicedigital.atlassian.net/browse/NXT-112
=> NXT-112 indicator chapter pages hydration fix

web/config/default.yml, web/src/pages/guidance/__tests__/__snapshots__/awaiting-development.page.test.tsx.snap, web/src/pages/guidance/__tests__/__snapshots__/inconsultation.page.test.tsx.snap, web/src/pages/guidance/__tests__/__snapshots__/indevelopment.page.test.tsx.snap, web/src/pages/guidance/__tests__/__snapshots__/published.page.test.tsx.snap, web/src/pages/guidance/__tests__/__snapshots__/topic-selection.page.test.tsx.snap, web/src/pages/guidance/awaiting-development.page.tsx, web/src/pages/guidance/inconsultation.page.tsx, web/src/pages/guidance/indevelopment.page.tsx, web/src/pages/guidance/published.page.tsx, web/src/pages/guidance/topic-selection.page.tsx
https://nicedigital.atlassian.net/browse/NXT-133
=> NXT-133 Fix URLs not being copied to clipboard

web/package-lock.json, web/package.json
https://nicedigital.atlassian.net/browse/NXT-141
=> NXT-141 Version bump global-nav

web/package-lock.json, web/package.json
https://nicedigital.atlassian.net/browse/NXT-142
=> NXT-142 GN version bump

web/src/pages/indicators/__tests__/__snapshots__/inconsultation.page.test.tsx.snap, web/src/pages/indicators/__tests__/__snapshots__/indevelopment.page.test.tsx.snap, web/src/pages/indicators/inconsultation.page.tsx, web/src/pages/indicators/indevelopment.page.tsx
https://nicedigital.atlassian.net/browse/NXT-144
=> NXT-144-Indicators-snagging-list

web/config/default.yml, web/src/config/config.ts, web/src/logging/nice-logging.ts
https://nicedigital.atlassian.net/browse/NXT-152
=> NXT-152 Add build number and Node version to Kibana logs

.vscode/extensions.json, web/src/components/SearchCard/SearchCardList.tsx
https://nicedigital.atlassian.net/browse/NXT-132
=> NXT-132 publication labels

functional-tests/package-lock.json, web/next.config.js, web/src/components/ProjectInformation/ProjectInformation.tsx, web/src/components/ProjectPageHeading/ProjectPageHeading.tsx, web/src/feeds/inDev/types.ts, web/src/pages/indicators/indevelopment/[slug]/__snapshots__/index.page.test.tsx.snap, web/src/pages/indicators/indevelopment/[slug]/index.page.tsx, web/src/utils/url.ts
https://nicedigital.atlassian.net/browse/NXT-156?atlOrigin=eyJpIjoiZjdhY2Q3ZDg4ZDY3NGM4ODg3NGY1YmYxOTA2MmQ4MzUiLCJwIjoiaiJ9
=> NXT-156 Add a new hub project page

web/jest.config.js, web/next.config.js, web/package-lock.json, web/package.json
https://nicedigital.atlassian.net/browse/NXT-169
=> NXT-169 Bump global nav version for drop support for ie 11 and upgrade dependencies

web/src/pages/_app.page.scss, web/styles/_global.scss, web/styles/_guidance-conversion.scss
Created new styles folder for global css partials.
=> NXT-166 Update spacing between section numbers and main content block

web/src/pages/forms/__snapshots__/leave-feedback.page.test.tsx.snap, web/src/pages/forms/leave-feedback.page.test.tsx, web/src/pages/forms/leave-feedback.page.tsx
https://nicedigital.atlassian.net/browse/NXT-158
=> NXT-158 leave feedback form

web/config/default.yml, web/config/test.js, web/jest.config.js, web/src/components/JotFormEmbed/JotFormEmbed.module.scss, web/src/components/JotFormEmbed/JotFormEmbed.test.tsx, web/src/components/JotFormEmbed/JotFormEmbed.tsx, web/src/components/JotFormPage/JotFormPage.test.tsx, web/src/components/JotFormPage/JotFormPage.tsx, web/src/components/JotFormPage/getGetServerSideProps.test.ts, web/src/components/JotFormPage/getGetServerSideProps.ts, web/src/config/config.ts, web/src/feeds/jotform/jotform.ts, web/src/feeds/jotform/types.ts, web/src/pages/forms/__snapshots__/interventional-procedures-notification.page.test.tsx.snap, web/src/pages/forms/__snapshots__/leave-feedback.page.test.tsx.snap, web/src/pages/forms/__snapshots__/use-of-nice-content-in-the-uk.page.test.tsx.snap, web/src/pages/forms/forms.module.scss, web/src/pages/forms/interventional-procedures-notification.page.test.tsx, web/src/pages/forms/interventional-procedures-notification.page.tsx, web/src/pages/forms/leave-feedback.page.test.tsx, web/src/pages/forms/leave-feedback.page.tsx, web/src/pages/forms/use-of-nice-content-in-the-uk.page.test.tsx, web/src/pages/forms/use-of-nice-content-in-the-uk.page.tsx
* NXT-149 Add IP notification form
* NXT-149 Add JotForm embed code
* NXT-149 Fix iframe resize with test
* NXT-149 Remove redundant webpack change
* NXT-149 Clairfy JotForm comment
* NXT-149 Fix comment
* NXT-149 Add JotForm page tests
* NXT-149 Add jot form page tests
* NXT-149 Update snapshots and jest config
* NXT-149 Fix linting issue with jotform css module
* NXT-149 Pre cherry pick conflict resolve
* NXT-149 Reintroduce deprecated scrolling attribute on jotform embed to test linting passes on tc
* NXT-149 Update snapshots
* NXT-149 Add optional informationPanel prop to JotFormPage component
* NXT-149 Update snapshots after layout changes
* NXT-149 Update heading level to be sequential
* NXT-149 Update snapshot
* NXT-149 Add missing form header and form footer content for uk open …
=> NXT-149 & NXT-151 Add IP notification and UK open content forms (#114)

web/src/pages/forms/__snapshots__/help-implement-nice-guidance.page.test.tsx.snap, web/src/pages/forms/help-implement-nice-guidance.page.test.tsx, web/src/pages/forms/help-implement-nice-guidance.page.tsx
https://nicedigital.atlassian.net/browse/NXT-179
=> NXT-179 Add help implement nice guidance form and test

web/src/pages/forms/__snapshots__/request-a-speaker.page.test.tsx.snap, web/src/pages/forms/request-a-speaker.page.test.tsx, web/src/pages/forms/request-a-speaker.page.tsx
https://nicedigital.atlassian.net/browse/NXT-177
=> NXT-177 Add request a speaker form and test

web/src/pages/forms/__snapshots__/leave-feedback.page.test.tsx.snap, web/src/pages/forms/leave-feedback.page.test.tsx, web/src/pages/forms/leave-feedback.page.tsx
https://nicedigital.atlassian.net/browse/NXT-183
=> NXT-183 Change feedback form title

web/next.config.js, web/package-lock.json, web/package.json, web/src/components/Storyblok/CategoryNavigation/CategoryNavigation.tsx, web/src/components/Storyblok/StoryblokHero/StoryblokHero.tsx, web/src/pages/_app.page.tsx, web/src/pages/about/[...slug].page.tsx, web/src/pages/about/index.page.tsx, web/src/pages/index.page.tsx, web/src/types/storyblok.d.ts, web/src/utils/storyblok.ts
https://nicedigital.atlassian.net/browse/NXT-185
=> Nxt 185 hero and catnav

web/next.config.test.ts, web/package-lock.json, web/package.json, web/src/__mocks__/@storyblok/react.ts, web/src/components/Storyblok/CategoryNavigation/CategoryNavigation.tsx, web/src/components/Storyblok/Homepage/Homepage.tsx, web/src/components/Storyblok/Metadata/Metadata.tsx, web/src/jest.setup.ts, web/src/pages/_app.page.tsx, web/src/pages/about/[...slug].page.tsx, web/src/pages/about/index.page.tsx, web/src/pages/index.page.tsx, web/src/pages/next-seo.config.ts, web/src/types/storyblok.d.ts, web/src/utils/storyblok.test.ts, web/src/utils/storyblok.ts
https://nicedigital.atlassian.net/browse/NXT-188
=> NXT-188 corporate page metadata

web/src/pages/indicators/indevelopment/[slug]/index.page.tsx
https://nicedigital.atlassian.net/browse/NXT-190
=> NXT-190 hub page fixes

web/src/pages/forms/__snapshots__/subscribe-to-update-for-primary-care.page.test.tsx.snap, web/src/pages/forms/subscribe-to-update-for-primary-care.page.test.tsx, web/src/pages/forms/subscribe-to-update-for-primary-care.page.tsx
https://nicedigital.atlassian.net/browse/NXT-193
=> NXT-193 Add primary care form and test

web/src/pages/forms/__snapshots__/subscribe-to-medicines-and-prescribing-important-new-evidence.page.test.tsx.snap, web/src/pages/forms/subscribe-to-medicines-and-prescribing-important-new-evidence.page.test.tsx, web/src/pages/forms/subscribe-to-medicines-and-prescribing-important-new-evidence.page.tsx
https://nicedigital.atlassian.net/browse/NXT-194
=> NXT-194 Add medicines and prescribing form and test

web/src/pages/forms/__snapshots__/subscribe-to-nice-news-international.page.test.tsx.snap, web/src/pages/forms/subscribe-to-nice-news-international.page.test.tsx, web/src/pages/forms/subscribe-to-nice-news-international.page.tsx
https://nicedigital.atlassian.net/browse/NXT-195
=> NXT-195 Add international newsletter form and test

web/src/pages/forms/__snapshots__/subscribe-to-medicine-and-prescribing-alerts.page.test.tsx.snap, web/src/pages/forms/subscribe-to-medicine-and-prescribing-alerts.page.test.tsx, web/src/pages/forms/subscribe-to-medicine-and-prescribing-alerts.page.tsx
https://nicedigital.atlassian.net/browse/NXT-196
=> NXT-196 Add medicines and prescribing alerts form and test

web/package-lock.json, web/package.json, web/src/pages/_app.test.tsx
https://nicedigital.atlassian.net/browse/NXT-207
=> NXT-207 Master version bump GN

web/package-lock.json, web/package.json
https://nicedigital.atlassian.net/browse/NXT-209
=> NXT-209 Bump global nav version

web/src/components/Storyblok/CategoryNavigation/CategoryNavigation.tsx, web/src/components/Storyblok/Homepage/Homepage.tsx, web/src/pages/[...slug].page.tsx
https://nicedigital.atlassian.net/browse/NXT-211
=> NXT-211 catch all routes

web/package-lock.json, web/package.json
https://nicedigital.atlassian.net/browse/NXT-212
=> NXT-212 Search client version bump

web/src/pages/forms/__snapshots__/subscribe-to-medicine-and-prescribing-alerts.page.test.tsx.snap, web/src/pages/forms/__snapshots__/subscribe-to-medicines-and-prescribing-important-new-evidence.page.test.tsx.snap, web/src/pages/forms/__snapshots__/subscribe-to-nice-news-for-health-and-social-care.page.test.tsx.snap, web/src/pages/forms/__snapshots__/subscribe-to-nice-news-for-life-sciences.page.test.tsx.snap, web/src/pages/forms/__snapshots__/subscribe-to-nice-news-international.page.test.tsx.snap, web/src/pages/forms/__snapshots__/subscribe-to-update-for-primary-care.page.test.tsx.snap, web/src/pages/forms/subscribe-to-medicine-and-prescribing-alerts.page.tsx, web/src/pages/forms/subscribe-to-medicines-and-prescribing-important-new-evidence.page.tsx, web/src/pages/forms/subscribe-to-nice-news-for-health-and-social-care.page.tsx, web/src/pages/forms/subscribe-to-nice-news-for-life-sciences.page.tsx, web/src/pages/forms/subscribe-to-nice-news-international.page.tsx, web/src/pages/forms/subscribe-to-update-for-primary-care.page.tsx
https://nicedigital.atlassian.net/browse/NXT-224
=> NXT-224 Update breadcrumb to reflect change on orchard

web/src/pages/forms/__snapshots__/public-involvement-programme-expert-panel-application.page.test.tsx.snap, web/src/pages/forms/public-involvement-programme-expert-panel-application.page.test.tsx, web/src/pages/forms/public-involvement-programme-expert-panel-application.page.tsx
https://nicedigital.atlassian.net/browse/NXT-203
=> NXT-203 Add public involvement form page and test

web/src/pages/index.page.tsx, web/src/types/News.d.ts, web/src/utils/storyblok.ts
https://nicedigital.atlassian.net/browse/NXT-250
=> NXT-250 Refactor fetchstories utility function

web/src/components/Storyblok/News/FeaturedStory/FeaturedStory.module.scss, web/src/components/Storyblok/News/FeaturedStory/FeaturedStory.tsx, web/src/components/Storyblok/News/FeaturedStory/__snapshots__/FeaturedStory.test.tsx.snap, web/src/components/Storyblok/News/NewsCard/NewsCard.module.scss, web/src/components/Storyblok/News/NewsCard/NewsCard.tsx, web/src/components/Storyblok/News/NewsCard/__snapshots__/NewsCard.test.tsx.snap
https://nicedigital.atlassian.net/browse/NXT-251
=> NXT-251 Refactor NewsCard component

web/src/components/Storyblok/NewsPageHeader/NewsPageHeaderFooter/NewsPageHeaderFooter.module.scss, web/src/components/Storyblok/StoryblokAuthor/StoryblokAuthor.module.scss, web/src/components/Storyblok/StoryblokBlogPost/StoryblokBlogPost.module.scss, web/src/components/Storyblok/StoryblokBlogPost/StoryblokBlogPost.tsx, web/src/components/Storyblok/StoryblokNewsArticle/StoryblokNewsArticle.module.scss, web/src/components/Storyblok/StoryblokNewsArticle/StoryblokNewsArticle.tsx, web/src/components/Storyblok/StoryblokRichText/StoryblokRichText.module.scss, web/src/components/Storyblok/StoryblokYoutubeEmbed/StoryblokYoutubeEmbed.module.scss
Updated styles to follow NICE-222.
- Various spacing tweaks
- Moved some nested grid items so Blog and News components are the same.
=> Nice 222 news blog style fixes

web/package-lock.json, web/package.json, web/src/components/Storyblok/Homepage/Homepage.tsx, web/src/components/Storyblok/Homepage/HomepageLatestNews/HomepageLatestNews.tsx, web/src/components/Storyblok/Spotlight/Spotlight.tsx, web/src/components/Storyblok/StoryblokActionBanner/StoryblokActionBanner.test.tsx, web/src/components/Storyblok/StoryblokActionBanner/StoryblokActionBanner.tsx, web/src/components/Storyblok/StoryblokActionBanner/__snapshots__/StoryblokActionBanner.test.tsx.snap, web/src/types/storyblok.d.ts
https://nicedigital.atlassian.net/browse/NICE-164
=> NICE-164 Implement Storyblok action banner

web/package-lock.json, web/package.json, web/src/components/Storyblok/CategoryNavigation/CategoryNavigation.tsx, web/src/components/Storyblok/Homepage/Homepage.module.scss, web/src/components/Storyblok/Homepage/Homepage.tsx, web/src/components/Storyblok/Homepage/HomepageHero/HomepageHero.tsx, web/src/components/Storyblok/InfoPage/InfoPage.module.scss, web/src/components/Storyblok/InfoPage/InfoPage.tsx, web/src/components/Storyblok/PromoBox/PromoBox.module.scss, web/src/components/Storyblok/PromoBox/PromoBox.tsx, web/src/components/Storyblok/PromoBox/__snapshots__/PromoBox.test.tsx.snap, web/src/components/Storyblok/StoryblokHero/StoryblokHero.tsx, web/src/components/Storyblok/StoryblokPageHeader/StoryblokPageHeader.tsx, web/src/pages/[...slug].page.tsx, web/src/types/storyblok.d.ts
https://nicedigital.atlassian.net/browse/NICE-226
=> NICE-226 draft info page

web/src/middleware.page.test.tsx, web/src/middleware.page.tsx, web/src/pages/standards-and-indicators/[indicatorType]/[slug].page.tsx
https://nicedigital.atlassian.net/browse/NXT-246
=> NXT-246 Indicator Old URL mixed casing - redirects not working correctly

web/src/pages/index.page.tsx
resolves https://nicedigital.atlassian.net/browse/NXT-269
=> NXT-269(fix): filter articles out of latest news with future date

web/src/components/Storyblok/News/FeaturedStory/FeaturedStory.tsx, web/src/components/Storyblok/News/NewsCard/NewsCard.tsx, web/src/components/Storyblok/PromoBox/PromoBox.tsx, web/src/components/Storyblok/PromoBox/__snapshots__/PromoBox.test.tsx.snap, web/src/components/Storyblok/StoryblokActionBanner/StoryblokActionBanner.tsx, web/src/components/Storyblok/StoryblokActionBanner/__snapshots__/StoryblokActionBanner.test.tsx.snap, web/src/components/Storyblok/StoryblokHero/StoryblokHero.tsx, web/src/components/Storyblok/StoryblokHero/__snapshots__/StoryblokHero.test.tsx.snap, web/src/pages/index.page.tsx, web/src/pages/news/podcasts/[slug].page.tsx, web/src/utils/storyblok.test.ts, web/src/utils/storyblok.ts
https://nicedigital.atlassian.net/browse/NICE-254
=> NICE-254 Handle image optimisation

web/src/components/Storyblok/News/FeaturedStory/FeaturedStory.tsx, web/src/components/Storyblok/News/NewsCard/NewsCard.tsx, web/src/components/Storyblok/PromoBox/PromoBox.tsx, web/src/components/Storyblok/StoryblokActionBanner/StoryblokActionBanner.tsx, web/src/components/Storyblok/StoryblokAuthor/AuthorList/AuthorList.tsx, web/src/components/Storyblok/StoryblokAuthor/StoryblokAuthor.module.scss, web/src/components/Storyblok/StoryblokBlogPost/StoryblokBlogPost.tsx, web/src/components/Storyblok/StoryblokHero/StoryblokHero.tsx, web/src/components/Storyblok/StoryblokRichText/StoryblokRichText.tsx, web/src/pages/news/podcasts/[slug].page.tsx, web/src/utils/storyblok.ts
Linked to issues raised on: https://nicedigital.atlassian.net/browse/NXT-292
=> Nxt 292 blog page fixes from feedback

web/src/components/Storyblok/News/NewsListPaginationAnnouncer/NewsListPaginationAnnouncer.tsx, web/src/components/Storyblok/News/NewsListPaginationFocus/NewsListPaginationFocus.test.tsx, web/src/components/Storyblok/News/NewsListPaginationFocus/NewsListPaginationFocus.tsx, web/src/hooks/usePaginationFocus.ts, web/src/pages/news/articles/index.page.tsx, web/src/pages/news/blogs/index.page.tsx, web/src/pages/news/in-depth/index.page.tsx, web/src/pages/news/index.page.tsx, web/src/pages/news/podcasts/index.page.tsx
https://nicedigital.atlassian.net/browse/NICE-250
=> NICE-250 Managing focus on pagination route changes

web/src/components/Storyblok/News/FeaturedStory/FeaturedStory.tsx, web/src/components/Storyblok/News/NewsCard/NewsCard.tsx, web/src/components/Storyblok/PromoBox/PromoBox.tsx, web/src/components/Storyblok/Spotlight/__snapshots__/Spotlight.test.tsx.snap, web/src/components/Storyblok/StoryblokActionBanner/StoryblokActionBanner.tsx, web/src/components/Storyblok/StoryblokHero/StoryblokHero.tsx, web/src/components/Storyblok/StoryblokImage/StoryblokImage.test.tsx, web/src/components/Storyblok/StoryblokImage/StoryblokImage.tsx, web/src/pages/news/podcasts/[slug].page.tsx, web/src/utils/storyblok.test.ts, web/src/utils/storyblok.ts
See: https://nicedigital.atlassian.net/browse/NICE-261
=> Nice 261 refactor image optimisation

web/src/components/Storyblok/Homepage/Homepage.module.scss, web/src/components/Storyblok/Homepage/Homepage.tsx, web/src/components/Storyblok/Homepage/HomepageHero/HomepageHero.module.scss, web/src/components/Storyblok/Homepage/HomepageLatestNews/HomepageLatestNews.module.scss, web/src/components/Storyblok/Homepage/HomepageLatestNews/HomepageLatestNews.tsx, web/src/components/Storyblok/Homepage/HomepageLatestNews/__snapshots__/HomepageLatestNews.test.tsx.snap, web/src/components/Storyblok/News/FeaturedStory/FeaturedStory.test.tsx, web/src/components/Storyblok/News/NewsCard/NewsCard.module.scss, web/src/components/Storyblok/News/NewsCard/NewsCard.test.tsx, web/src/components/Storyblok/News/NewsCard/NewsCard.tsx, web/src/components/Storyblok/News/NewsCard/__snapshots__/NewsCard.test.tsx.snap, web/src/components/Storyblok/News/NewsGrid/__snapshots__/NewsGrid.test.tsx.snap, web/src/components/Storyblok/PromoBox/PromoBox.module.scss, web/src/components/Storyblok/PromoBox/PromoBox.tsx, web/src/components/Storyblok/PromoBox/__snapshots__/PromoBox.test.tsx.snap, web/src/components/Storyblok/Spotlight/Spotlight.module.scss, web/src/components/Storyblok/Spotlight/Spotlight.tsx, web/src/components/Storyblok/Spotlight/__snapshots__/Spotlight.test.tsx.snap, web/src/components/Storyblok/StoryblokYoutubeEmbed/StoryblokYoutubeEmbed.module.scss, web/src/pages/__snapshots__/index.test.tsx.snap, web/src/pages/news/blogs/index.page.tsx, web/src/pages/news/index.page.tsx, web/src/utils/storyblok.ts, web/styles/_spacing.scss
Compound ticket for miscellaneous QA fixes
=> Nice 266 homepage spacing

web/src/feeds/inDev/types.ts, web/src/utils/product.ts
https://nicedigital.atlassian.net/browse/NXT-337
=> NXT-337 Fix for empty product panel

web/src/components/NewsLetterSignUp/NewsLetterSignup.tsx, web/src/components/SoundCloudEmbed/SoundCloudEmbed.tsx, web/src/components/Storyblok/Homepage/HomepageLatestNews/HomepageLatestNews.tsx, web/src/components/Storyblok/News/NewsCard/NewsCard.module.scss, web/src/components/Storyblok/News/NewsCard/NewsCard.tsx, web/src/components/Storyblok/StoryblokBlogPost/StoryblokBlogPost.module.scss, web/src/components/Storyblok/StoryblokNewsArticle/StoryblokNewsArticle.module.scss, web/src/pages/news/articles/index.page.tsx, web/src/pages/news/blogs/index.page.tsx, web/src/pages/news/in-depth/index.page.tsx, web/src/pages/news/index.module.scss, web/src/pages/news/podcasts/[slug].page.tsx, web/src/pages/news/podcasts/index.page.tsx, web/src/pages/news/podcasts/podcast.module.scss, web/src/utils/initStoryblok.ts, web/styles/_global.scss, web/styles/_spacing.scss
Contains fixes for multiple tickets in the latest round of QA
=> NICE-283 spacing again

README.md, api/NICE.NextWeb.API/NICE.NextWeb.API.csproj, api/NICE.NextWeb.API/Startup.cs, api/NICE.NextWeb.API/appsettings.Development.json, api/NICE.NextWeb.API/appsettings.Production.json, api/NICE.NextWeb.API/ocelot.production.json, web/config/default.yml, web/src/config/config.ts, web/src/utils/initStoryblok.ts, web/src/utils/storyblok.ts
https://nicedigital.atlassian.net/browse/NXT-217
=> NXT-217 Use Ocelot for Storyblok cacheing

web/src/pages/[...slug].page.tsx
https://nicedigital.atlassian.net/browse/NICE-291
=> NICE-291 Return 404 for root catch all unless env var enables it

web/config/default.yml, web/src/config/config.ts, web/src/pages/[...slug].page.tsx, web/src/pages/env-test.page.tsx, web/src/utils/initStoryblok.ts, web/src/utils/storyblok.ts
https://nicedigital.atlassian.net/browse/NXT-346
=> NXT-346 Revert env var config, add test page

web/next.config.js
https://nicedigital.atlassian.net/browse/NXT-369
=> NXT-369 Add redirects for news section

README.md, aws/readme.md, web/README.md, web/next.config.js, web/package-lock.json
Resolving merge conflicts when pulling from main
=> Storyblok merge main

web/package-lock.json, web/src/components/NewsLetterSignUp/NewsLetterSignup.tsx, web/src/pages/forms/__snapshots__/subscribe-to-medicine-and-prescribing-alerts.page.test.tsx.snap, web/src/pages/forms/__snapshots__/subscribe-to-medicines-and-prescribing-important-new-evidence.page.test.tsx.snap, web/src/pages/forms/__snapshots__/subscribe-to-nice-news-for-health-and-social-care.page.test.tsx.snap, web/src/pages/forms/__snapshots__/subscribe-to-nice-news-for-life-sciences.page.test.tsx.snap, web/src/pages/forms/__snapshots__/subscribe-to-nice-news-international.page.test.tsx.snap, web/src/pages/forms/__snapshots__/subscribe-to-update-for-primary-care.page.test.tsx.snap, web/src/pages/forms/subscribe-to-medicine-and-prescribing-alerts.page.tsx, web/src/pages/forms/subscribe-to-medicines-and-prescribing-important-new-evidence.page.tsx, web/src/pages/forms/subscribe-to-nice-news-for-health-and-social-care.page.tsx, web/src/pages/forms/subscribe-to-nice-news-for-life-sciences.page.tsx, web/src/pages/forms/subscribe-to-nice-news-international.page.tsx, web/src/pages/forms/subscribe-to-update-for-primary-care.page.tsx, web/src/pages/news/__snapshots__/index.page.test.tsx.snap, web/src/pages/news/articles/__snapshots__/[slug].page.test.tsx.snap, web/src/pages/news/articles/__snapshots__/index.page.test.tsx.snap, web/src/pages/news/blogs/__snapshots__/[slug].page.test.tsx.snap, web/src/pages/news/blogs/__snapshots__/index.page.test.tsx.snap, web/src/pages/news/in-depth/__snapshots__/index.page.test.tsx.snap, web/src/pages/news/podcasts/__snapshots__/index.page.test.tsx.snap
https://nicedigital.atlassian.net/browse/NXT-380
=> NXT-380 Update newsletter signup URL and related snapshots/references

web/config/default.yml, web/src/config/config.ts, web/src/pages/_app.page.tsx
https://nicedigital.atlassian.net/browse/NXT-382
=> NXT-382 auth environment config

web/next.config.js, web/src/config/config.ts, web/src/pages/api/robots.api.test.ts, web/src/pages/api/robots.api.ts, web/src/test-utils/string.ts
https://nicedigital.atlassian.net/browse/NICE-306
=> NICE-306 Configure robots.txt for live & non-live environments

web/next.config.js
https://nicedigital.atlassian.net/browse/NXT-386
=> NXT-386 Add new news redirects

aws/terraform/main.tf, aws/terraform/terraform.tfvars, aws/terraform/variables.tf
https://nicedigital.atlassian.net/browse/NXT-370
=> NXT-370 Add datetime to NextWeb config dir name

web/styles/_global.scss
https://nicedigital.atlassian.net/browse/NXT-391
=> NXT-391 Fix inconsistent font rendering

web/src/utils/storyblok.test.ts, web/src/utils/storyblok.ts
https://nicedigital.atlassian.net/browse/NXT-395
=> NXT-395 (NW-1917) Make date formatting errors fail more gracefully

web/README.md, web/package-lock.json, web/package.json, web/syncScript.mjs
https://nicedigital.atlassian.net/browse/NICE-310
=> NXT-402 set up migration between different storyblok environments (NICE-310)

web/config/default.yml, web/src/config/config.ts, web/src/pages/api/robots.api.test.ts, web/src/pages/api/robots.api.ts
https://nicedigital.atlassian.net/browse/NXT-392
=> NXT-392 Update type for denyRobots flag

web/next.config.js
https://nicedigital.atlassian.net/browse/NXT-336
=> NXT-336 Add indicators/published redirect

web/src/components/ProductListPage/ProductListGetServerSideProps/ProductListGetServerSideProps.test.ts, web/src/pages/guidance/__tests__/__snapshots__/inconsultation.page.test.tsx.snap, web/src/pages/guidance/__tests__/__snapshots__/indevelopment.page.test.tsx.snap, web/src/pages/guidance/inconsultation.page.tsx, web/src/pages/guidance/indevelopment.page.tsx
https://nicedigital.atlassian.net/browse/NXT-407
=> NXT-407 Switch sort order from date ascending to descending

web/src/feeds/publications/publications.ts
https://nicedigital.atlassian.net/browse/NXT-411
=> NXT-411 Change getChapterContent and getResourceDetail calls to use longTTL

web/src/pages/forms/__snapshots__/life-sciences-contact-us.page.test.tsx.snap, web/src/pages/forms/life-sciences-contact-us.page.test.tsx, web/src/pages/forms/life-sciences-contact-us.page.tsx
https://nicedigital.atlassian.net/browse/NXT-421
=> NXT-421 Life sciences enquiry form update jotform

web/README.md, web/package.json, web/pullPushScript.mjs
https://nicedigital.atlassian.net/browse/NXT-422
=> NXT-422 Add script to manage push pull of components between spaces on storyblok

web/src/components/Link/Link.tsx, web/src/components/ProductListPage/ProductListFilterSummary/ProductListFilterSummary.tsx, web/src/components/ProductListPage/ProductListPage.test.tsx, web/src/components/ProjectHorizontalNav/ProjectHorizontalNav.test.tsx, web/src/hooks/useScrollToTarget.ts, web/src/pages/indicators/__tests__/published.page.test.tsx
https://nicedigital.atlassian.net/browse/NXT-432 
Completed work along with John Davey.
=> NXT-432 Fix broken scroll to links in nextweb guidance list pages

web/src/__mocks__/__data__/publications/newfeeds/areaofinteresttypes.json, web/src/feeds/publications/__snapshots__/publications.test.ts.snap, web/src/feeds/publications/publications.test.ts, web/src/feeds/publications/publications.ts, web/src/feeds/publications/types.ts
https://nicedigital.atlassian.net/browse/NXT-438
=> NXT-438-Switch NextWeb to use new areaofinteresttypes feed

web/src/pages/forms/__snapshots__/use-of-nice-content-in-the-uk.page.test.tsx.snap, web/src/pages/forms/use-of-nice-content-in-the-uk.page.tsx
https://nicedigital.atlassian.net/browse/NXT-430
=> NXT-430 Update NICE UK open content licence

.gitignore, web/src/pages/forms/__snapshots__/life-sciences-contact-us.page.test.tsx.snap, web/src/pages/forms/__snapshots__/nice-content-assurance-service.page.test.tsx.snap, web/src/pages/forms/__snapshots__/permission-request-form-for-international-use-of-nice-content.page.test.tsx.snap, web/src/pages/forms/__snapshots__/request-for-prioritisation-clarification.page.test.tsx.snap, web/src/pages/forms/__snapshots__/syndication-service-application-form.page.test.tsx.snap, web/src/pages/forms/__snapshots__/topic-suggestion.page.test.tsx.snap, web/src/pages/forms/life-sciences-contact-us.page.test.tsx, web/src/pages/forms/life-sciences-contact-us.page.tsx, web/src/pages/forms/nice-content-assurance-service.page.test.tsx, web/src/pages/forms/nice-content-assurance-service.page.tsx, web/src/pages/forms/permission-request-form-for-international-use-of-nice-content.page.test.tsx, web/src/pages/forms/permission-request-form-for-international-use-of-nice-content.page.tsx, web/src/pages/forms/request-for-prioritisation-clarification.page.test.tsx, web/src/pages/forms/request-for-prioritisation-clarification.page.tsx, web/src/pages/forms/syndication-service-application-form.page.test.tsx, web/src/pages/forms/syndication-service-application-form.page.tsx, web/src/pages/forms/topic-suggestion.page.test.tsx, web/src/pages/forms/topic-suggestion.page.tsx
https://nicedigital.atlassian.net/browse/NXT-443
=> NXT-462, NXT-460, NXT-448, NXT-447, NXT-446, NXT-444, NXT-443 jotforms feature branch

web/src/components/ProductResourceChapterPage/ProductResourceChapterPage.tsx, web/src/components/ProductResourcePage/ProductResourcePage.module.scss, web/src/components/ProductResourcePage/ProductResourcePage.test.tsx, web/src/components/ProductResourcePage/ProductResourcePage.tsx, web/src/components/ProductResourcePage/__snapshots__/ProductResourcePage.test.tsx.snap, web/src/feeds/publications/types.ts, web/src/pages/indicators/[slug]/resources/[partSlug]/chapter/__snapshots__/[chapterSlug].page.test.tsx.snap, web/src/utils/contentparts.ts, web/src/utils/resource.ts, web/src/utils/url.test.ts, web/src/utils/url.ts
https://nicedigital.atlassian.net/browse/NXT-426 
FIX BELOW
fetchAndMapContentParts function was recently added for the feed update work - contentPartList2.
Function was returning an array regardless of whether it had found the correct type using the filter. Function now returns undefined and will return an object as well as an array.
The types for contentParts has also been updated to allow an object as well as an array for when there are multiple parts.
=> NXT-426 Autogenerated PDF version for indicator resources

web/README.md
https://nicedigital.atlassian.net/browse/NXT-481
=> NXT-481: Update Readme to setup local next-web to point to local publications

web/README.md, web/pullPushScript.mjs, web/syncScript.mjs
https://nicedigital.atlassian.net/browse/NXT-497
=> NXT-497 Add command to speed up type generation

web/src/components/ProductListPage/ProductListPage.tsx, web/src/components/SearchNoResults/SearchNoResults.tsx, web/src/components/SearchNoResults/__snapshots__/SearchNoResults.test.tsx.snap
https://nicedigital.atlassian.net/browse/NXT-464
=> NXT-464 Edit the no search result page topic link (uses ?)

web/.gitignore, web/src/components/ErrorPageContent/ErrorPageContent.tsx, web/src/components/ErrorPageContent/__snapshots__/ErrorPageContent.test.tsx.snap, web/src/pages/404.page.tsx, web/src/pages/404.test.tsx, web/src/pages/__snapshots__/index.test.tsx.snap, web/src/pages/news/__snapshots__/index.page.test.tsx.snap, web/src/pages/news/articles/__snapshots__/[slug].page.test.tsx.snap, web/src/pages/news/articles/__snapshots__/index.page.test.tsx.snap, web/src/pages/news/blogs/__snapshots__/[slug].page.test.tsx.snap, web/src/pages/news/blogs/__snapshots__/index.page.test.tsx.snap, web/src/pages/news/in-depth/__snapshots__/index.page.test.tsx.snap, web/src/pages/news/podcasts/__snapshots__/[slug].page.test.tsx.snap, web/src/pages/news/podcasts/__snapshots__/index.page.test.tsx.snap
https://nicedigital.atlassian.net/browse/NXT-433
=> NXT-433 Replace out of date we cant find this page with one on rest of site

web/src/components/SearchSections/SearchSections.tsx
https://nicedigital.atlassian.net/browse/NXT-534
=> NXT-534 Fix search recs and qs links

web/src/pages/forms/subscribe-to-medicines-and-prescribing-important-new-evidence.page.test.tsx, web/src/pages/forms/subscribe-to-medicines-and-prescribing-important-new-evidence.page.tsx
https://nicedigital.atlassian.net/browse/NXT-454
=> NXT-454 change page title and page intro

web/src/pages/forms/subscribe-to-medicines-and-prescribing-important-new-evidence.page.tsx
https://nicedigital.atlassian.net/browse/NXT-541
=> NXT-541 Comment out gssp to fix 404 error on decommissioned form page

web/src/components/Storyblok/Spotlight/__snapshots__/Spotlight.test.tsx.snap, web/src/components/Storyblok/StoryblokImage/StoryblokImage.tsx, web/src/components/Storyblok/StoryblokTestimonialFullWidth/__snapshots__/StoryblokTestimonialFullWidth.test.tsx.snap, web/src/components/Storyblok/StoryblokTestimonialGridItem/__snapshots__/StoryblokTestimonialGridItem.test.tsx.snap, web/src/pages/__snapshots__/index.test.tsx.snap, web/src/pages/news/articles/__snapshots__/[slug].page.test.tsx.snap, web/src/pages/news/blogs/__snapshots__/[slug].page.test.tsx.snap
https://nicedigital.atlassian.net/browse/NXT-542
=> NXT-542 Added layout="intrinsic" to <Image/> to maintain image's intrinsic size

functional-tests/wdio.conf.ts
https://nicedigital.atlassian.net/browse/NXT-559
=> NXT-559 Comment out research recommendation functional tests

web/src/components/Storyblok/StoryblokRichText/StoryblokRichText.module.scss, web/src/pages/[...slug].page.tsx, web/src/types/storyblok.d.ts
https://nicedigital.atlassian.net/browse/NXT-551
=> NXT-551 Added ActionBannerDefault to infopage

web/package-lock.json, web/package.json
https://nicedigital.atlassian.net/browse/NXT-568
=> NXT-568 Version bump global nav

web/src/components/Storyblok/PromoBox/PromoBox.tsx, web/src/components/Storyblok/StoryblokActionBanner/StoryblokActionBannerDefault.module.scss, web/src/components/Storyblok/StoryblokActionBanner/StoryblokActionBannerDefault.tsx, web/src/components/Storyblok/StoryblokActionBanner/__snapshots__/StoryblokActionBannerDefault.test.tsx.snap
https://nicedigital.atlassian.net/browse/NXT-554
=> Nxt 554 fix margins for default action banner

web/package-lock.json, web/package.json
https://nicedigital.atlassian.net/browse/NXT-579
=> NXT-579 Bump global nav

web/src/pages/forms/__snapshots__/public-involvement-programme-expert-panel-application.page.test.tsx.snap, web/src/pages/forms/public-involvement-programme-expert-panel-application.page.test.tsx, web/src/pages/forms/public-involvement-programme-expert-panel-application.page.tsx
https://nicedigital.atlassian.net/browse/NXT-517
http://localhost:4000/forms/public-involvement-programme-expert-panel-application
=> Nxt 517 changes to jotform title and breadcrumb

web/src/pages/forms/__snapshots__/nice-health-technology-assessment-training-registration.page.test.tsx.snap, web/src/pages/forms/nice-health-technology-assessment-training-registration.page.test.tsx, web/src/pages/forms/nice-health-technology-assessment-training-registration.page.tsx
https://nicedigital.atlassian.net/browse/NXT-530
http://localhost:4000/forms/nice-health-technology-assessment-training-registration
=> NXT-530-Migrated-form-to-Jotforms-new

api/NICE.NextWeb.API/Startup.cs, api/NICE.NextWeb.API/ocelot.production.json
https://nicedigital.atlassian.net/browse/NXT-572
=> NXT-572 Add v2 Storyblok api to Ocelot

web/src/components/Storyblok/StoryblokTestimonialFullWidth/StoryblokTestimonialFullWidth.tsx, web/src/components/Storyblok/StoryblokTestimonialGridItem/StoryblokTestimonialGridItem.tsx, web/src/components/Testimonial/Testimonial.test.tsx, web/src/components/Testimonial/Testimonial.tsx, web/src/types/storyblok.d.ts
Storyblok Components Changed:
- [Testimonial Grid Item](https://app.storyblok.com/#/me/spaces/292509/components/6891922)
- [Testimonial Full Width](https://app.storyblok.com/#/me/spaces/292509/components/6891919)
=> NXT-570 Update testimonial to make profile image optional

functional-tests/wdio.conf.ts
https://nicedigital.atlassian.net/browse/NXT-624
=> NXT-624: comment out feature test

web/src/pages/indicators/indevelopment/[slug]/index.page.tsx
https://nicedigital.atlassian.net/browse/NXT-616
=> NXT-616-IND-Add bullet points on related links list

web/src/pages/forms/__snapshots__/interventional-procedures-notification.page.test.tsx.snap, web/src/pages/forms/interventional-procedures-notification.page.tsx
https://nicedigital.atlassian.net/browse/NXT-631
=> NXT-631 Remove duplicate link

web/src/components/Storyblok/CardList/CardList.module.scss, web/src/components/Storyblok/CardList/CardList.test.tsx, web/src/components/Storyblok/CardList/CardList.tsx, web/src/components/Storyblok/CardListSection/CardListSection.test.tsx, web/src/components/Storyblok/CardListSection/__snapshots__/CardListSection.test.tsx.snap
https://nicedigital.atlassian.net/browse/NICE-422
https://nicedigital.atlassian.net/browse/NXT-634
=> NXT-634 update card list component to fix summary text

web/src/pages/_app.page.tsx, web/src/pages/_app.test.tsx
https://nicedigital.atlassian.net/browse/NXT-648
=> NXT-648 Fix active nav section for hub global nav

.vscode/extensions.json, web/next-sitemap.config.js, web/public/sitemap-static.xml, web/src/pages/sitemap-next.xml.page.tsx, web/src/utils/storyblok.ts
https://nicedigital.atlassian.net/browse/NXT-645?atlOrigin=eyJpIjoiMmM3YjUzMTdmNWJjNGY3NzliYWY4YjgzZGI3MmVmYTEiLCJwIjoiaiJ9
Can preview on local using live token
=> NXT-645-update-sitemaps-with-new-ur-ls-of-pages-included-in-phase-2-test-launch

web/next.config.js
https://nicedigital.atlassian.net/browse/NXT-683
=> NXT-683 update Direct Awards redirect to reflect correct origin url

web/src/pages/indicators/[slug]/evidence/index.page.tsx, web/src/pages/indicators/[slug]/history/__snapshots__/index.page.test.tsx.snap, web/src/pages/indicators/[slug]/history/index.page.tsx, web/src/pages/indicators/[slug]/resources/__snapshots__/index.page.test.tsx.snap, web/src/pages/indicators/[slug]/resources/index.page.tsx, web/src/pages/indicators/indevelopment/[slug]/documents/__snapshots__/index.page.test.tsx.snap, web/src/pages/indicators/indevelopment/[slug]/documents/index.page.tsx
https://nicedigital.atlassian.net/browse/NXT-690
=> NXT-690 Descriptors missing from tabs in indicators

web/package-lock.json, web/package.json, web/src/components/Storyblok/StoryblokSectionNav/StoryblokSectionNav.module.scss, web/src/components/Storyblok/StoryblokSectionNav/StoryblokSectionNav.tsx
https://nicedigital.atlassian.net/browse/NDS-468
=> NXT-702 Add word wrap break word to stacked nav content wrapper

web/src/components/OnThisPage/OnThisPage.module.scss, web/src/components/OnThisPageBasic/OnThisPageBasic.test.tsx, web/src/components/OnThisPageBasic/OnThisPageBasic.tsx, web/src/components/ProductResourceChapterPage/ProductResourceChapterPage.tsx, web/src/components/ProductResourcePage/ProductResourcePage.tsx, web/src/components/ProductResourcePage/__snapshots__/ProductResourcePage.test.tsx.snap, web/src/pages/indicators/[slug]/chapter/[chapterSlug].page.tsx, web/src/pages/indicators/[slug]/chapter/__snapshots__/[chapterSlug].page.test.tsx.snap, web/src/pages/indicators/[slug]/resources/[partSlug]/chapter/__snapshots__/[chapterSlug].page.test.tsx.snap
https://nicedigital.atlassian.net/browse/NXT-708
=> Nxt 708 move on this page section over the chapter content to match gw for indicators

functional-tests/features/guidancePagination.feature
https://nicedigital.atlassian.net/browse/NXT-754
=> NXT-754 Fix functional test issue by introducing scrolling step

functional-tests/features/guidancePagination.feature
https://nicedigital.atlassian.net/browse/NXT-755
=> NXT-755 Fix functional test issue in teamcity

web/next.config.js
https://nicedigital.atlassian.net/browse/NXT-779
=> NXT-779 update broken Types of Recommendation redirects

web/src/pages/forms/__snapshots__/subscribe-to-our-gp-reference-panel.page.test.tsx.snap, web/src/pages/forms/subscribe-to-our-gp-reference-panel.page.tsx
https://nicedigital.atlassian.net/browse/NXT-773
=> Nxt 773 update text on gp reference panel subscription form page jotform
